### ISSUE TITLE
minor issues

### ISSUE THREAD

**Issue by xialeiliu** [fcdl94/MiB#14]
what is run_inc.py in the command line? it is not in the folder。
Which pretrained model do you use from https://github.com/mapillary/inplace_abn#training-on-imagenet-1k?

I tried several but I got errors:

 model = make_model(opts, classes=tasks.get_per_task_classes(opts.dataset, opts.task, opts.step))
  File "/home/xialei/MiB/segmentation_module.py", line 29, in make_model
    del pre_dict['state_dict']['classifier.fc.weight']
KeyError: 'classifier.fc.weight'

Thanks!

**Comment by xialeiliu** [comment]
I think I understood what you mean by run_inc.py, which should be the same run.py but using different step, right?

For second question, I realized that I downloaded a pretrained model which is trained and saved with multiple gpus. It contains "module" before all keys in the state_dict, which should be removed. I know how to solve it now.

If what I am saying is correct, then feel free to close this issue. Thanks.

**Comment by fcdl94** [comment]
Thank you for pointing out the issue with run_inc. That was a copy and paste mistake.

As for the second question, you're right. The pretrained model contains the module.xxx in every key since it was trained with DistributedDataParallel. Thanks for pointing this out, I'll add it to the readme. Removing "module." is simple, since it's just a matter of renaming the keys removing the first 7 characters.

Thank you, if there are no other comments, I will close the issue in a few days.

**Comment by ygjwd12345** [comment]
@xialeiliu I also face this problem. can you tell me how to solve this problem?
