### ISSUE TITLE
Code for generating data splits

### ISSUE THREAD

**Issue by yulu0724** [fcdl94/MiB#15]
Hi,

Could you please share the code for generating data splits under data/ folder, it is convenient to use default splits such as (19-1, 15-5, 15-5s, 100-50), but It would be good to have the code, I am interested in some different splits.

BTW, I found the split voc 15-5s step-0 seems wrong, but I can use the one from 15-5, they should be the same.

Thanks.

**Comment by fcdl94** [comment]
Hi!
Yes, the split for 15-5s is missing since I always used the pretrained made on the 15-5 task. Sorry about that, find you solved. I will copy and paste also in the repo.

About the code for the splits:
* For Pascal-VOC the code to generate the splits can be found directly in the dataset. https://github.com/fcdl94/MiB/blob/e74fb8d1b1bb72b393eaa102d5a9c4eb82daf009/dataset/voc.py#L138 Changing the overlap flag allows you to generate the "overlapped" version or the disjoint one.
* For ADE-20K, the splits were made using a jupyter notebook which I need to clean up before publishing. I hope to be able to upload it before the weekend.

**Comment by fcdl94** [comment]
Hi!
I managed to clean the code and I uploaded the script to split the ADE20K dataset.
See it here: https://github.com/fcdl94/MiB/blob/master/ADE-Split.ipynb
However, I don't guarantee that you can re-create the same split used in my paper since I lost the actual seed to generate mine (but you can find the splits I utilized in the _data_ folder of this repo).

Hope you can find it clear, but if you have any question, please comment on this issue.
Otherwise, if there are no additional comments, I will close the issue. 👍

**Comment by yulu0724** [comment]
Many thanks!!!
