### ISSUE TITLE
I have a little question about the data of table1

### ISSUE THREAD

**Issue by nachifur** [fcdl94/MiB#20]
![image](https://user-images.githubusercontent.com/23144348/91972313-19d6e580-ed4d-11ea-9bf5-d73a5e4dfb54.png)

![image](https://user-images.githubusercontent.com/23144348/91972543-74704180-ed4d-11ea-947d-56ab5dc101f5.png)

I think the training results  should be the **same at 1-15** for Single-step addition of five classes (15-5) and Multi-step addition of five classes (15-1).
Isn’t it different the last five times?
You have referenced the following documents:Incremental Learning of Object Detectors without Catastrophic Forgetting
I verified my idea in this article. Did I understand it wrong? Or is it a mistake in the article?
![image](https://user-images.githubusercontent.com/23144348/91973354-b3eb5d80-ed4e-11ea-92bb-c281c695387e.png)
Thanks for your reply, the article idea is great!

**Comment by fcdl94** [comment]
Hi @nachifur!
Sorry, I think the paper should be clearer. 
They are not the results of the network after learning those 15 classes, but they are the results after learning all the classes.
In that case, the results differ since in the 15-5 we made a single step of 5 classes, while on the 15-1 we made 5 steps of 1 class. 
To be even clear, I used the same pretrained on the first 15 classes for both the 15-5, 15-1, so that not only the results are the same, but also the network weights :)

**Comment by nachifur** [comment]
@fcdl94 Thanks for your reply. Now, I have understood the data of table 1. 😁

**Comment by fcdl94** [comment]
@nachifur Can I close the issue?

**Comment by nachifur-ljw** [comment]
Yes, thank you!

**Comment by nachifur** [comment]
@fcdl94 Yes, thank you!
