### ISSUE TITLE
Question about init_balanced: why "-log(N+1)" operation is need in bias initialization?

### ISSUE THREAD

**Issue by EricKani** [fcdl94/MiB#29]
same as title~

Thanks!

**Comment by fcdl94** [comment]
HI @EricKani.
The goal is to distribute the "old" background probability to the "new" background and to novel classes.
To do so, what we need to do is (1) set the weights for novel classes as the background, and (2) transform the bias of both novel classes and background to make sure that new_probability = old_bkg_proability / (| new_classes | +1), where +1 represent the bkg class.

You can see the equations 8 and 9 in the paper. In Eq. 9, we use -log(|C^t| ) since |C^t| equals to (| new_classes | +1).

**Comment by fcdl94** [comment]
Hi @EricKani.
Is it clear why I used that equation? Can I close the issue?

**Comment by EricKani** [comment]
Sorry for late response... I understand how the implementation works to a large extent. Thanks a lot~
But I still don't understand "log" 's role here... Could you explain that in more detail? Thank you very much!

**Comment by fcdl94** [comment]
Hi @EricKani,
Sorry for the too-late response.
The role of the log is to split the background probability on background old and new classes. That has been derived from some math equations, imposing that the probability of old bkg class was equally divided on novel classes.
